version: "3.7"
services:
    app:
        build:
            args:
                user: task-management-user
                uid: 1000
            context: ..
            dockerfile: .docker/Dockerfile
        image: task-management
        container_name: task-management
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - task-management-network

    nginx:
        image: nginx:alpine
        container_name: task-management-nginx
        restart: unless-stopped
        ports:
            - "8005:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - task-management-network

networks:
    task-management-network:
        driver: bridge
